/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author Design
 */
public class Cell extends javax.swing.JPanel {

    /**
     * Creates new form Cell
     */
    public Cell() {
        initComponents();
        Dimension panelSize = new Dimension(100, 100);
        background.setSize(panelSize);
        background.setPreferredSize(panelSize);
        background.setMaximumSize(panelSize);
        background.setMinimumSize(panelSize);
        background.setLocation(0,0);
    }
    
    public Cell(Double wordToSet,int indexToSet) {
        initComponents();
        Dimension panelSize = new Dimension(100, 100);
        background.setSize(panelSize);
        background.setPreferredSize(panelSize);
        background.setMaximumSize(panelSize);
        background.setMinimumSize(panelSize);
        background.setLocation(0,0);
        index.setText(String.valueOf(indexToSet));
        word.setText(String.valueOf(wordToSet));
    }
    
    public void setWord(String word){
        this.word.setText("<html>"+word+"</html>");
    }
    public void setindex(String index){
        this.index.setText(index);
    }
    public void setColor(Color color){
        this.background.setBackground(color);
    }
    public String getWord(){
        return this.word.getText();
    }
    public String getindex(){
        return this.index.getText();
    }
    public Color getColor(){
        return this.background.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        word = new javax.swing.JLabel();
        index = new javax.swing.JLabel();
        indexText = new javax.swing.JLabel();
        wordText = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(null);

        word.setBackground(new java.awt.Color(46, 204, 113));
        word.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        word.setForeground(new java.awt.Color(255, 255, 255));
        word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        word.setText("123456789123");
        word.setToolTipText("2ecc71");
        add(word);
        word.setBounds(6, 20, 90, 50);

        index.setBackground(new java.awt.Color(52, 152, 219));
        index.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        index.setForeground(new java.awt.Color(255, 255, 255));
        index.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        index.setText("123456789123");
        index.setToolTipText("");
        add(index);
        index.setBounds(0, 80, 100, 20);

        indexText.setBackground(new java.awt.Color(255, 255, 255));
        indexText.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        indexText.setForeground(new java.awt.Color(255, 255, 255));
        indexText.setText("Index");
        add(indexText);
        indexText.setBounds(10, 60, 90, 30);

        wordText.setBackground(new java.awt.Color(255, 255, 255));
        wordText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        wordText.setForeground(new java.awt.Color(255, 255, 255));
        wordText.setText("Word");
        add(wordText);
        wordText.setBounds(10, 0, 110, 20);

        background.setBackground(new java.awt.Color(44, 62, 80));
        background.setOpaque(true);
        add(background);
        background.setBounds(2, -2, 100, 100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel index;
    private javax.swing.JLabel indexText;
    private javax.swing.JLabel word;
    private javax.swing.JLabel wordText;
    // End of variables declaration//GEN-END:variables
}
